////////////////////////////
//Lydia Cornwell
//CSE 2
//Network.java - a program that displays a window into a network of boxes connected by lines generated by user input

import java.util.Scanner;

public class Network {
  public static void main(String[] args) {

    Scanner myScanner = new Scanner(System.in);

    System.out.print("Input your desired height: ");
    boolean heightTest = true;
    int height = 0;
    while (heightTest) {
      if (myScanner.hasNextInt()) {
        height = myScanner.nextInt();
        if (height > 0) {
          heightTest = false;
        } else {
          System.out.println("Error, please type in an integer");
        }
      } else {
        System.out.println("Error, please type in an integer");
        myScanner.next();
      }
    }

    System.out.print("Input your desired width: ");
    boolean widthTest = true;
    int width = 0;
    while (widthTest) {
      if (myScanner.hasNextInt()) {
        width = myScanner.nextInt();
        if (width > 0) {
          widthTest = false;
        } else {
          System.out.println("Error, please type in an integer");
        }
      } else {
        System.out.println("Error, please type in an integer");
        myScanner.next();
      }
    }

    System.out.print("Input square size: ");
    boolean sizeTest = true;
    int size = 0;
    while (sizeTest) {
      if (myScanner.hasNextInt()) {
        size = myScanner.nextInt();
        if (size > 0) {
          sizeTest = false;
        } else {
          System.out.println("Error, please type in an integer");
        }
      } else {
        System.out.println("Error, please type in an integer");
        myScanner.next();
      }
    }

    System.out.print("Input edge length: ");
    boolean edgeTest = true;
    int edge = 0;
    while (edgeTest) {
      if (myScanner.hasNextInt()) {
        edge = myScanner.nextInt();
        if (edge > 0) {
          edgeTest = false;
        } else {
          System.out.println("Error, please type in an integer");
        }
      } else {
        System.out.println("Error, please type in an integer");
        myScanner.next();
      }
    }

    int repeating = edge + size;
    

    for (int i = 0; i < height; i++) {
      for (int j = 0; j < width; j++) {
        //corner points
        if (((j % repeating == 0 && i % repeating == 0) || (j % repeating + 1 == size && i % repeating == 0)) || 
          ((j % repeating == 0 && i % repeating + 1 == size || (j % repeating + 1== size && i % repeating + 1 == size)))) {
          System.out.print("#");
        } else if ((j % repeating + 1 < size && j % repeating > 0) && (i % repeating == 0 || i % repeating + 1 == size)) {
          System.out.print("-");
        } else if ((i % repeating + 1 < size && i % repeating > 0) && (j % repeating == 0 || j % repeating + 1 == size)) {
          System.out.print("|");
          
          
        } else if (size % 2 == 0 && (i % repeating + 1 > size && (j % repeating ==(int) (size/2) || j % repeating == (int) ((size/2) - 1)))) {
          System.out.print("|");
        } else if (size % 2 == 1 && i % repeating +1 > size && (j % repeating == (int) (size/2))) {
          System.out.print("|");
        } else if (size % 2 == 0 && j % repeating + 1 > size && ((i % repeating == (int) (size/2)  || i % repeating == (int) ((size/2) - 1)))) {
         System.out.print("-");
        } else if (size % 2 == 1 && j % repeating + 1> size  && (i % repeating == (int) (size/2))) {
          System.out.print("-");
          
      
        } else {
          System.out.print(" ");
        }
      }
      System.out.println();
    }
  }
}